# Dockerfile for flutter project
# AUTHOR jon "imyme6yo@gmail.com"
# CREATE DATE 190115
# UPDATE DATE 190117

ARG VERSION=1.0
ARG TAG=${VERSION}-ubuntu18.04

FROM imyme6yo/flutter:${TAG}

LABEL maintainer "imyme6yo@gmail"

ARG DIR_NAME=code
ARG PROJECT_NAME=project

RUN yes | flutter doctor --android-licenses || true

RUN mkdir ${DIR_NAME}
ADD . ${DIR_NAME}
WORKDIR ${DIR_NAME}

RUN npm install
