# @AUTHOR jon "imyme6yo@gmail.com"
# @DATE 190115
ARG VERSION=1.0

FROM imyme6yo/flutter:${VERSION}-ubuntu18.04

LABEL maintainer "imyme6yo@gmail"

ARG DIRNAME=project_code

RUN flutter create ${DIRNAME}

WORKDIR ${DIRNAME}