# @AUTHOR: jon "imyme6yo@gmail.com"
# @DRAFT:
# @UPDATE:
# @DESCRIPTION:
#           dd

ARG ANGULAR_VERSION=7

FROM baseimage

# Labels
# Maintainer
LABEL maintainer="jon"
LABEL email="imyme6yo@gmail.com"
